---
#
# Copyright 2014 Major Hayden
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
#

  - name: 4.1 Restrict core dumps (Scored) - via pam
    lineinfile: >
      dest=/etc/security/limits.conf
      line="* hard core 0"
      insertafter=EOF
      create=yes
    sudo: yes
    tags:
      - scored
      - section4.1

  - name: 4.1 Restrict core dumps (Scored) - via sysctl
    sysctl: >
      name=fs.suid_dumpable
      value=0
      state=present
      ignoreerrors=yes
    sudo: yes
    tags:
      - scored
      - section4.1

  - name: 4.1 Restrict Core Dumps (Scored) - via apt
    action: apt pkg={{item}} state=absent
    with_items:
      - whoopsie
      - apport
    sudo: yes
    tags:
      - scored
      - section4.1

  - name: 4.2 Enable XD/NX Support on 32-bit x86 Systems (Not Scored)
    debug: msg="*** Not relevant for x64 architecture."
    tags:
      - notscored
      - section4.2
  
  - name: 4.3 Enable Randomized Virtual Memory Region Placement (Scored)
    sysctl: >
      name=kernel.randomize_va_space
      value=2
      state=present
      ignoreerrors=yes
    sudo: yes
    tags:
      - scored
      - section4.3

  - name: 4.4 Disable Prelink (Scored)
    apt: pkg=prelink state=absent
    sudo: yes
    tags:
      - scored
      - section4.4
