---
#
# Copyright 2014 Major Hayden
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
#

  - name: 9.1.1 Enable cron Daemon (Scored)
    service: >
      name=cron
      enabled=yes
      state=started
    sudo: yes
    tags:
      - scored
      - section9.1
      - section9.1.1

  - name: 9.1.2-9.1.7 Set User/Group Owner and Permission on cron files (Scored)
    file: >
      path={{ item.path }}
      state={{ item.state }}
      owner={{ item.owner }}
      group={{ item.group }}
      mode={{ item.mode }}
    with_items:
      - { path: /etc/crontab, state: file, owner: root, group: root, mode: "0600" }
      - { path: /etc/cron.hourly, state: directory, owner: root, group: root, mode: "0600" }
      - { path: /etc/cron.daily, state: directory, owner: root, group: root, mode: "0600" }
      - { path: /etc/cron.weekly, state: directory, owner: root, group: root, mode: "0600" }
      - { path: /etc/cron.monthly, state: directory, owner: root, group: root, mode: "0600" }
      - { path: /etc/cron.d, state: directory, owner: root, group: root, mode: "0600" }
    sudo: yes
    tags:
      - scored
      - section9.1
      - section9.1.2
      - section9.1.3
      - section9.1.4
      - section9.1.5
      - section9.1.6
      - section9.1.7

  - name: 9.1.8 Restrict at/cron to Authorized Users (Scored)
    file: >
      path={{ item.path }}
      state={{ item.state }}
      owner={{ item.owner }}
      group={{ item.group }}
      mode={{ item.mode }}
    with_items:
      - { path: /etc/at.deny, state: absent, owner: root, group: root, mode: "0000" }
      - { path: /etc/at.allow, state: touch, owner: root, group: root, mode: "0600" }
      - { path: /etc/cron.deny, state: absent, owner: root, group: root, mode: "0000" }
      - { path: /etc/cron.allow, state: touch, owner: root, group: root, mode: "0600" }
    sudo: yes
    tags:
      - scored
      - section9.1
      - section9.1.8

  - name: 9.2.1 Set Password Creation Requirement Parameters Using pam_cracklib (Scored)
    lineinfile: >
      dest=/etc/pam.d/common-password
      line="password required pam_cracklib.so retry=3 minlen=14 dcredit=-1 ucredit=-1 ocredit=-1 lcredit=-1"
      regexp="^password required pam cracklib.so"
      insertafter=EOF
      create=yes
    sudo: yes
    tags:
      - scored
      - section9.2
      - section9.2.1

  - name: 9.2.2 Set Lockout for Failed Password Attempts (Not Scored)
    lineinfile: >
      dest=/etc/pam.d/login
      line="auth required pam_tally2.so onerr=fail audit silent deny=5 unlock_time=900"
      regexp="^auth required pam_tally2.so"
      insertafter=EOF
      create=yes
    sudo: yes
    tags:
      - notscored
      - section9.2
      - section9.2.2

  - name: 9.2.3 Limit Password Reuse (Scored)
    lineinfile: >
      dest=/etc/pam.d/common-password
      line="password sufficient pam_unix.so remember=5"
      regexp="^password sufficient pam_unix.so"
      insertafter=EOF
      create=yes
    sudo: yes
    tags:
      - scored
      - section9.2
      - section9.2.3

  - name: 9.3.1 Set SSH Protocol to 2 (Scored)
    lineinfile: >
      dest=/etc/ssh/sshd_config
      line="Protocol 2"
      regexp="^Protocol "
    sudo: yes
    notify: Reload sshd
    tags:
      - scored
      - section9.3
      - section9.3.1

  - name: 9.3.2 Set LogLevel to INFO (Scored)
    lineinfile: >
      dest=/etc/ssh/sshd_config
      regexp="^LogLevel "
      line="LogLevel INFO"
    sudo: yes
    notify: Reload sshd
    tags:
      - scored
      - section9.3
      - section9.3.2

  - name: 9.3.3 Set Permissions on /etc/ssh/sshd_config (Scored)
    file: >
      path=/etc/ssh/sshd_config
      owner=root
      group=root
      mode=0600
    sudo: yes
    notify: Reload sshd
    tags:
      - scored
      - section9.3
      - section9.3.3

  - name: 9.3.4 Disable SSH X11 Forwarding (Scored)
    lineinfile: >
      dest=/etc/ssh/sshd_config
      regexp="^X11Forwarding "
      line="X11Forwarding no"
    sudo: yes
    notify: Reload sshd
    tags:
      - scored
      - section9.3
      - section9.3.4

  - name: 9.3.5 Set SSH MaxAuthTries to 4 or Less (Scored)
    lineinfile: >
      dest=/etc/ssh/sshd_config
      regexp="^MaxAuthTries "
      line="MaxAuthTries 4"
    sudo: yes
    notify: Reload sshd
    tags:
      - scored
      - section9.3
      - section9.3.5

  - name: 9.3.6 Set SSH IgnoreRhosts to Yes (Scored)
    lineinfile: >
      dest=/etc/ssh/sshd_config
      regexp="^IgnoreRhosts "
      line="IgnoreRhosts yes"
    sudo: yes
    notify: Reload sshd
    tags:
      - scored
      - section9.3
      - section9.3.6

  - name: 9.3.7 Set SSH HostbasedAuthentication to No (Scored)
    lineinfile: >
      dest=/etc/ssh/sshd_config
      regexp="^HostbasedAuthentication "
      line="HostbasedAuthentication no"
    sudo: yes
    notify: Reload sshd
    tags:
      - scored
      - section9.3
      - section9.3.7

  - name: 9.3.8 Disable SSH Root Login (Scored)
    lineinfile: >
      dest=/etc/ssh/sshd_config
      regexp="^PermitRootLogin "
      line="PermitRootLogin no"
    sudo: yes
    notify: Reload sshd
    tags:
      - scored
      - section9.3
      - section9.3.8

  - name: 9.3.9 Set SSH PermitEmptyPasswords to No (Scored)
    lineinfile: >
      dest=/etc/ssh/sshd_config
      regexp="^PermitEmptyPasswords "
      line="PermitEmptyPasswords no"
    sudo: yes
    notify: Reload sshd
    tags:
      - scored
      - section9.3
      - section9.3.9

  - name: 9.3.10 Do Not Allow Users to Set Environment Options (Scored)
    lineinfile: >
      dest=/etc/ssh/sshd_config
      regexp="^PermitUserEnvironment "
      line="PermitUserEnvironment no"
    sudo: yes
    notify: Reload sshd
    tags:
      - scored
      - section9.3
      - section9.3.10

  - name: 9.3.11 Use Only Approved Cipher in Counter Mode (Scored)
    lineinfile: >
      dest=/etc/ssh/sshd_config
      regexp="^Ciphers "
      line="Ciphers aes128-ctr,aes192-ctr,aes256-ctr"
    sudo: yes
    notify: Reload sshd
    tags:
      - scored
      - section9.3
      - section9.3.11

  - name: 9.3.12 Set Idle Timeout Interval for User Login (Scored)
    lineinfile: >
      dest=/etc/ssh/sshd_config
      line="{{ item.line }}"
      regexp="{{ item.regexp }}"
    sudo: yes
    with_items:
      - { line: "ClientAliveInterval 300", regexp: "^ClientAliveInterval " }
      - { line: "ClientAliveCountMax 0", regexp: "^ClientAliveCountMax " }
    notify: Reload sshd
    tags:
      - scored
      - section9.3
      - section9.3.12

  - name: 9.3.13 Limit Access via SSH (Scored)
    lineinfile: >
      dest={{ item.dest }}
      regexp={{ item.regexp }}
      line="{{ item.line }} {{item.linetarget}}"
    with_items:
      - { dest: /etc/ssh/sshd_config, regexp: "^AllowGroups ", line: "AllowGroups", linetarget: "{{ ssh_allow_groups|default('') }}" }
      - { dest: /etc/ssh/sshd_config, regexp: "^AllowUsers ", line: "AllowUsers", linetarget: "{{ ssh_allow_users|default('') }}" }
      - { dest: /etc/ssh/sshd_config, regexp: "^DenyGroups ", line: "DenyGroups", linetarget: "{{ ssh_deny_groups|default('') }}" }
      - { dest: /etc/ssh/sshd_config, regexp: "^DenyUsers ", line: "DenyUsers", linetarget: "{{ ssh_deny_users|default('') }}" }
    when: item.linetarget != ''
    sudo: yes
    notify: Reload sshd
    tags:
      - scored
      - section9.3
      - section9.3.13

  - name: 9.3.14 Set SSH Banner (Scored)
    lineinfile: >
      dest=/etc/ssh/sshd_config
      regexp="^Banner "
      line="Banner /etc/issue.net"
    sudo: yes
    notify: Reload sshd
    tags:
      - scored
      - section9.3
      - section9.3.14

  - name: 9.4 Restrict root Login to System Console (Not Scored)
    debug: msg="Too restrictive for most environments."
    tags:
      - notscored
      - section9.4

  - name: 9.5 Restrict Access to the su Command (Scored) - create wheel group
    group: name=wheel
    sudo: yes
    tags:
      - scored
      - section9.5

  - name: 9.5 Restrict Access to the su Command (Scored) - add root to wheel
    user: >
      name=root
      groups=wheel
      append=yes
    sudo: yes
    tags:
      - scored
      - section9.5

  - name: 9.5 Restrict Access to the su Command (Scored) - pam.d su file
    lineinfile: >
      dest=/etc/pam.d/su
      line="auth required pam_wheel.so use_uid"
      regexp="^auth required pam_wheel.so"
      insertafter=EOF
      create=yes
    sudo: yes
    tags:
      - scored
      - section9.5
